import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "@/app/Providers";
import { NextUIProvider } from "@nextui-org/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "PCEI Tungurahua",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextUIProvider>
          <Providers>{children}</Providers>
        </NextUIProvider>
        {/* <Providers>{children}</Providers> */}
      </body>
    </html>
  );
}
