-- CreateTable
CREATE TABLE "ASISTENCIA" (
    "id" SERIAL NOT NULL,
    "idCalificacion" INTEGER NOT NULL,
    "porcentaje" DOUBLE PRECISION NOT NULL,

    CONSTRAINT "ASISTENCIA_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "CONDUCTA" (
    "id" SERIAL NOT NULL,
    "idCalificacion" INTEGER NOT NULL,
    "puntaje" DOUBLE PRECISION NOT NULL,

    CONSTRAINT "CONDUCTA_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "ASISTENCIA" ADD CONSTRAINT "ASISTENCIA_idCalificacion_fkey" FOREIGN KEY ("idCalificacion") REFERENCES "CALIFICACION"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CONDUCTA" ADD CONSTRAINT "CONDUCTA_idCalificacion_fkey" FOREIGN KEY ("idCalificacion") REFERENCES "CALIFICACION"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
