-- CreateTable
CREATE TABLE `Usuario` (
    `ID_USU` INTEGER NOT NULL AUTO_INCREMENT,
    `ID_CAM_PER` INTEGER NOT NULL,
    `NOM1_USU` VARCHAR(50) NULL,
    `NOM2_USU` VARCHAR(50) NULL,
    `APE1_USU` VARCHAR(50) NULL,
    `APE2_USU` VARCHAR(50) NULL,
    `COR_USU` VARCHAR(100) NULL,
    `CON_USU` VARCHAR(255) NULL,
    `CED_USU` VARCHAR(10) NULL,
    `EST_USU` BOOLEAN NULL,

    PRIMARY KEY (`ID_USU`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Campus` (
    `ID_CAM` INTEGER NOT NULL AUTO_INCREMENT,
    `NOM_CAM` VARCHAR(50) NULL,
    `DIR_CAM` VARCHAR(100) NULL,

    PRIMARY KEY (`ID_CAM`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Rol` (
    `ID_ROL` INTEGER NOT NULL AUTO_INCREMENT,
    `ROL` VARCHAR(50) NULL,

    PRIMARY KEY (`ID_ROL`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Detalle_rol` (
    `ID_DET_ROL` INTEGER NOT NULL AUTO_INCREMENT,
    `ID_USU_PER` INTEGER NOT NULL,
    `ID_ROL_PER` INTEGER NOT NULL,

    PRIMARY KEY (`ID_DET_ROL`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
